### ISSUE TITLE
关于Demo无法正常运行的问题

### ISSUE THREAD

**Issue by zgsgs** [vitdocjs/vitdoc#1]
环境: Windows 11
node版本: v16.15.1

按 README 步骤运行, 结果报错如下
![image](https://user-images.githubusercontent.com/22882957/189115521-1f69e937-9e22-40dd-a583-cadebc48601e.png)

怀疑可能是 Windows 系统原因吧, 希望大佬看一下, 很想上手体验一下!谢谢!

**Comment by yee94** [comment]
[bfcdcbe603e2d48c3e4b77d647173735a2375483](https://github.com/vitdocjs/vitdoc/commit/bfcdcbe603e2d48c3e4b77d647173735a2375483)

已处理解决，安装1.0.13版本即可启动

**Comment by zgsgs** [comment]
很完美!辛苦了!
